# Generated by Django 4.0.3 on 2022-05-02 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_remove_measurement_time_remove_project_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='access_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectuser',
            name='last_access',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
